const CategoriesArray = [
    {ID: 0, categName: "Electronics"},
    {ID: 1, categName: "Tools"},
    {ID: 2, categName: "Accesories"},
    {ID: 3, categName: "Bags"}
];

// This is going to be the Descriptions
var Desc1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";
var Desc2 = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.";
var Desc3 = "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
var Desc4 = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.";
var Desc5 = "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.";
var Desc6 = "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.";
var Desc7 = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?";
var Desc8 = "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.";
var Desc9 = "Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.";
var Desc10 = "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.";
var Desc11 = "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.";
var Desc12 = "Et maxime Quis qui unde similique et reiciendis iste aut illum autem rem deleniti eum quia laborum et consequatur voluptas. Non illum sunt et libero possimus qui error dolor sed architecto pariatur vel maiores adipisci vel tempore blanditiis.";
var Desc13 = "Rerum dolorem nam dignissimos Quis ut minima aliquam in dolorem quia aut iusto nesciunt aut internos enim.";
var Desc14 = "Ea minima tempora et dolorem accusamus ut quibusdam omnis et nobis maiores. At provident odit est iure dolore ut voluptatibus expedita eum impedit quibusdam ut obcaecati dolor.";

// This is going to be the Reviews
var Rev1 = "<h4>Saul Goodman</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod. </p> <h4>Walter White</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev2 = "<h4>Ethan Hunt</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod. </p> <h4>Benji Dunn</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev3 = "<h4>Master Chief</h4> <p>Ut laboriosam quia aut minima voluptates ut unde rerum. Ea iure pariatur hic magni fugiat aut quibusdam error ut nobis placeat. Et optio fugit qui doloribus ratione sed expedita architecto ab maxime dolorum quo voluptas possimus. </p> <h4>Cortana</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev4 = "<h4>Hudson Central</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod. </p> <h4>Lily Shen</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev5 = "<h4>Anakin Skywalker</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod. </p> <h4>Luke Skywalker</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev6 = "<h4>Padme Amidala</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod. </p> <h4>Leia Amidala</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev7 = "<h4>Matt Horner</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Valerian Mengsk</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev8 = "<h4>Mira Han</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Admiral Orlan</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev9 = "<h4>Tony Stark</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Pepper Potts</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev10 = "<h4>Dark Prelate Zeratul</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Matriach Vorazun</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev11 = "<h4>Highlord Alarak</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Ascendant Ji'nara</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev12 = "<h4>Hierarch Artanis</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Executor Selendis</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev13 = "<h4>Arcturus Mengsk</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Nova Terra</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";
var Rev14 = "<h4>James Raynor</h4> <p>Lorem ipsum dolor sit amet. Et sequi accusamus sed nulla quam et animi ipsa ut neque rerum eum quaerat voluptates et earum unde. Est totam commodi nam minima omnis At enim quod.</p> <h4>Sarah Kerrigan</h4> <p>Non esse iusto ab laudantium ducimus et dignissimos atque et neque magnam et quia nulla eum molestiae iure et ratione quas. Eum omnis possimus ut consequatur modi ut doloremque obcaecati ut repellat architecto. Ea provident eveniet et voluptatem veniam aut dolores expedita. Ab perferendis architecto sit explicabo autem et incidunt repellendus et accusantium quasi et dolores accusamus!</p>";


const ProductsArray = [
    {ID: 0, productName: "Sunsang Note 3D0",                     categID: 0, img:"images/CategoryProducts/Smartphone.webp",         price:10, description: Desc1,  type: 0, review: Rev1, qty:0},
    {ID: 1, productName: "Ranger VI Power Laptop v12",           categID: 0, img:"images/CategoryProducts/Laptop.webp",             price:15, description: Desc2,  type: 0, review: Rev2, qty:0},
    {ID: 2, productName: "Legion x1000 Power Drill",             categID: 1, img:"images/CategoryProducts/PowerDrill.jpg",          price:20, description: Desc3,  type: 0, review: Rev3, qty:0},
    {ID: 3, productName: "Bronx All-Purpose Swiss Army Knife",   categID: 1, img:"images/CategoryProducts/SwissArmyKnife.webp",     price:25, description: Desc4,  type: 0, review: Rev4, qty:0},
    {ID: 4, productName: "Starcraft Dominion Keychain",          categID: 2, img:"images/CategoryProducts/Keychain.webp",           price:30, description: Desc5,  type: 0, review: Rev5, qty:0},
    {ID: 5, productName: "Dark Souls Ring Collection",           categID: 2, img:"images/CategoryProducts/RingCollection.jpg",      price:35, description: Desc5,  type: 0, review: Rev6, qty:0},
    {ID: 6, productName: "Napkan Survival Knapsack",             categID: 3, img:"images/CategoryProducts/SurvivalBackpack.webp",   price:40, description: Desc7,  type: 0, review: Rev7, qty:0},
    {ID: 7, productName: "ChopItAll Machete Deluxe",             categID: 3, img:"images/CategoryProducts/Machete.jpg",             price:45, description: Desc8,  type: 0, review: Rev8, qty:0},
    // This is for the New Arrivals
    {ID: 8, productName: "Asus® Archon Laptop v8.2",             categID: 4, img:"images/New Arrivals/Laptop.png",                  price:50, description: Desc9,  type: 1, review: Rev9, qty:0},
    {ID: 9, productName: "Nydex® Heavy Duty Travel Backpack",    categID: 4, img:"images/New Arrivals/Backpack.jpg",                price:60, description: Desc10, type: 1, review: Rev10, qty:0},
    {ID: 10, productName: "Fixd® All Purpose Toolbox",           categID: 4, img:"images/New Arrivals/Toolbox.jpg",                 price:70, description: Desc11, type: 1, review: Rev11, qty:0},

    // This is for the Discounts
    {ID: 11, productName: "Grandiose Perak Keris Letter Opener", categID: 5, img:"images/Discounts/LetterOpener.jpg",               price:80, description: Desc12, type: 2, review: Rev12, qty:0},
    {ID: 12, productName: "FlexSaw Heavy Duty Hacksaw",          categID: 5, img:"images/Discounts/Saw.jpg",                        price:90, description: Desc13, type: 2, review: Rev13, qty:0},
    {ID: 13, productName: "Succital Quiet Vacuum Cleaner",       categID: 5, img:"images/Discounts/Vacuum.jpg",                     price:100, description: Desc14, type: 2, review: Rev14, qty:0}
];

